# Generated by Django 2.1.1 on 2018-11-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='problem',
            field=models.CharField(default='', max_length=200),
        ),
    ]
